spring:
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    static-path-pattern: /static/**

# The http configuration part for integration with other system
retrofit:
  connection:
    readTimeout: 5
    writeTimeout: 5
    connectTimeout: 5
    maxIdleConnections: 5 # The maximum number of idle connections for each address.
    keepAliveDuration: 5 # The time (minutes) to live for each idle connections.
    retryTimes: 1

  # identity: current available
  # baseUrl: the base part of business system url, would be changed by nginx location, "/" is not required to be the end of url
  endpoints:
  - identity: data-api
    baseUrl: http://api.caipiaokong.com/
  log:
    enabled: true
    content: BODY # NONE, BASIC, HEADERS, BODY
    level: INFO

lottofetish:
  uid: 922421
  token: ff2b5d0a13160f1367de26394e618a633df232b4
  format: json

